server:
  port: 8080

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.springbootmybatisdemo.domain


# logger
logging:
    config: classpath:logback.xml

# 指定执行环境
spring:
  profiles:
    active: @package.environment@